<?php if (!empty($links)) : ?>
<div class="input-group file-input" id="<?php echo $this->getName();?>_file">
	<span class="input-group-btn">
		<button class="btn btn-default remove-btn" type="button">&times;</button>
	</span>
	
	<?php if (!empty($links['thumb'])) : ?> 
    <img class="img-rounded" src="<?php echo $links['thumb']; ?>" />
    <?php elseif (!empty($links['file'])) :?>
    <a href="<?php echo $links['file']; ?>"><?php echo $fileName; ?></a>
    <?php endif; ?>

</div><!-- /input-group -->
<?php endif; ?>
<div id="<?php echo $this->getName();?>_file_upload" class="<?php if (!empty($links)) : ?>hidden<?php endif;?>">
    <input type="file" name="<?php echo $this->getName(); ?>" 
    	class="form-control <?php echo $this->getCssClassName(); ?>" />
    <input type="hidden" name="_<?php echo $this->getName(); ?>" 
    	value="<?php echo $value; ?>" />
</div>

<script>
(function (jQuery, containerFieldId, uploadFieldId) {
	var $container = jQuery('#' + containerFieldId)
		, $uploadContainer = jQuery('#' + uploadFieldId);

	jQuery('.remove-btn', $container).on('click', function () {
		$container.remove();
		$uploadContainer.removeClass('hidden')
			.find('[type="hidden"]').val('');
	});
})(jQuery, "<?php echo $this->getName();?>_file", "<?php echo $this->getName();?>_file_upload");
</script>